on:
  push:
    branches: [ main, feature/*, bugfix/*, task/*, PROD-* ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      newServiceVersion: ${{ steps.set-env-var.outputs.PROJECT_VERSION }}
    steps:
      - name: Check out the main repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check out the build script
        uses: actions/checkout@v4
        with:
          repository: hausinc-net/main-branch-action
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: .github/do_build

      - name: Do the build
        uses: ./.github/do_build
        with:
          name: Slack-Service
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up JDK 11 if 17 is not specified
        if: ${{ inputs.java_version == '' || inputs.java_version != '17' }}
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up JDK 17 if specified
        if: ${{ inputs.java_version == '17' }}
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Docker Buildx
        id: buildx
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/setup-buildx-action@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: gradle caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: clean, compile, run tests, scan libraries, generate documentation
        run: ./gradlew clean test assemble
        shell: bash

      - name: set project version var
        shell: bash
        run: |
          echo "PROJECT_VERSION=$(./gradlew properties -q | grep "^version:" | awk '{print $2}')" >> $GITHUB_ENV

      # Create git tag when merged to main OR to a branch prefixed with 'hotfix'
      - name: tag
        # fail the build when trying to publish duplicate tag
        continue-on-error: false
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ inputs.github_token }}
          tag: ${{env.PROJECT_VERSION}}
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/hotfix') ) }}

      - name: Check for existence of api docs
        id: check_api_doc
        uses: andstor/file-existence-action@v3
        with:
          files: "build/apidoc"

      - name: generate doc
        run: |
          if test -f "build/apidoc/openapi.json"; then
            sudo npm install -g redoc-cli@0.13.2
            redoc-cli bundle -o build/apidoc/docs-${{PROJECT_VERSION}}.html build/apidoc/openapi.json
            cp build/apidoc/openapi.json build/apidoc/docs-${{PROJECT_VERSION}}.json
          fi
        shell: bash
        if: steps.check_api_doc.outputs.files_exists == 'true'

      - name: publish docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build/apidoc
          target-folder: ${{env.PUB_DIR}}
          clean: false
        if: steps.check_api_doc.outputs.files_exists == 'true'